"""create users table

Revision ID: 9e2cbd82380f
Revises: 9c9b103d04cf
Create Date: 2025-05-04 20:49:29.548917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2cbd82380f'
down_revision: Union[str, None] = '9c9b103d04cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
